# Generated by Django 2.2.12 on 2020-05-05 18:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrgInfoCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(max_length=200, unique=True)),
                (
                    "org_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            (
                                "casc",
                                "Community Amateur Sports Clubs regulated by HMRC",
                            ),
                            ("ccew", "Registered charities in England and Wales"),
                            ("ccni", "Registered charities in Northern Ireland"),
                            ("oscr", "Registered charities in Scotland"),
                            (
                                "companies",
                                "Companies registered with Companies House (the scraper only imports non-profit company types)",
                            ),
                            (
                                "mutuals",
                                "Mutual societies registered with the Financial Conduct Authority",
                            ),
                            ("gor", "A register of government organisations"),
                            (
                                "grid",
                                "Entries from the Global Research Identifier Database - only those that are based in the UK and are not a registered company are included.",
                            ),
                            (
                                "hesa",
                                "Organisations covered by the Higher Education Statistics Agency.",
                            ),
                            ("lae", "Register of local authorities in England"),
                            (
                                "lani",
                                "Register of local authorities in Northern Ireland",
                            ),
                            ("las", "Register of local authorities in Scotland"),
                            ("pla", "Register of principal local authorities in Wales"),
                            ("nhsods", "NHS organisations"),
                            ("rsl", "Registered social landlords"),
                            (
                                "schools_gias",
                                "Schools in England (also includes Universities)",
                            ),
                            ("schools_ni", "Schools in Northern Ireland"),
                            ("schools_scotland", "Schools in Scotland"),
                            ("schools_wales", "Schools in Wales"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fetched", models.DateTimeField(auto_now=True)),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
