# Generated by Django 2.2.12 on 2020-05-22 16:36

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orginfocache",
            name="org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100),
                blank=True,
                db_index=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="orginfocache",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["org_ids"], name="additional__org_ids_6ac868_gin"
            ),
        ),
    ]
