# Generated by Django 2.2.10 on 2020-05-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_data', '0002_auto_20200522_1636'),
        ('additional_data', '0004_auto_20200522_1802'),
    ]

    operations = [
    ]
