# Generated by Django 2.2.13 on 2020-09-16 14:20

from django.db import migrations, models

import additional_data.models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_data", "0005_geolookup"),
    ]

    operations = [
        migrations.CreateModel(
            name="TSGOrgType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        help_text="Regex pattern to match the funder org-id",
                        max_length=200,
                        validators=[additional_data.models.TSGOrgType.validate_regex],
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Which pattern will take precedence", unique=True
                    ),
                ),
                (
                    "tsg_org_type",
                    models.CharField(
                        help_text="Value that will be added to the additional data",
                        max_length=200,
                        unique=True,
                        verbose_name="ThreeSixtyGiving Org Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "ThreeSixtyGiving Org Type",
                "ordering": ["priority"],
            },
        ),
    ]
