# Generated by Django 3.2.16 on 2023-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_data", "0007_auto_20200918_0954"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoCodeName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=9)),
                ("data", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="CodeName",
        ),
        migrations.AlterField(
            model_name="geolookup",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="nspl",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="orginfocache",
            name="data",
            field=models.JSONField(),
        ),
    ]
