# Generated by Django 3.2.20 on 2023-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_data', '0009_codelistcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelistcode',
            name='list_name',
            field=models.CharField(help_text='The name of the codelist the code belongs to', max_length=200),
        ),
    ]
