# Generated by Django 3.2.16 on 2024-05-17 21:23

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_data", "0011_alter_orginfocache_org_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="IMDWardLookup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wd23cd", models.TextField(help_text="2023 Ward Code")),
                ("wd23nm", models.TextField(help_text="2023 Ward Name (English)")),
                (
                    "wd23nmw",
                    models.TextField(help_text="2023 Ward Name (Welsh)", null=True),
                ),
                ("uk_imd_e_score", models.FloatField()),
                ("original_decile", models.PositiveSmallIntegerField()),
                ("e_expanded_decile", models.PositiveSmallIntegerField()),
                ("uk_imd_e_rank", models.FloatField()),
                ("uk_imd_e_pop_decile", models.PositiveSmallIntegerField()),
                ("uk_imd_e_pop_quintile", models.PositiveSmallIntegerField()),
                ("total_population", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="imdwardlookup",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["wd23cd"], name="additional__wd23cd_79e62a_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="imdwardlookup",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["wd23cd"], name="additional__wd23cd_1f1098_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="imdwardlookup",
            constraint=models.UniqueConstraint(
                fields=("wd23cd",), name="additional_data_imd_ward_lookup_unique_wd23cd"
            ),
        ),
    ]
