# Generated by Django 4.2.28 on 2026-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_data", "0013_alter_orginfocache_org_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistryFunder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salesforce_id", models.CharField(max_length=32, unique=True)),
                (
                    "org_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("fetched", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField()),
            ],
        ),
    ]
