# Generated by Django 4.2.21 on 2026-01-30 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_data", "0013_alter_orginfocache_org_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orginfocache",
            name="org_id",
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name="orginfocache",
            name="org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=2000),
                blank=True,
                db_index=True,
                null=True,
                size=None,
            ),
        ),
    ]
