# Generated by Django 4.2.28 on 2026-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_data", "0013_alter_orginfocache_org_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orginfocache",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("casc", "Community Amateur Sports Clubs regulated by HMRC"),
                    ("ccew", "Registered charities in England and Wales"),
                    ("ccni", "Registered charities in Northern Ireland"),
                    ("oscr", "Registered charities in Scotland"),
                    (
                        "companies",
                        "Companies registered with Companies House (the scraper only imports non-profit company types)",
                    ),
                    (
                        "mutuals",
                        "Mutual societies registered with the Financial Conduct Authority",
                    ),
                    ("gor", "A register of government organisations"),
                    (
                        "ror",
                        "Research Organisation Registry (formerly GRID) - only those that are based in the UK and are not a registered company are included.",
                    ),
                    ("coe", "Church of England"),
                    ("officeforstudents", "Office for Students"),
                    (
                        "hesa",
                        "Organisations covered by the Higher Education Statistics Agency.",
                    ),
                    ("lae", "Register of local authorities in England"),
                    ("lani", "Register of local authorities in Northern Ireland"),
                    ("las", "Register of local authorities in Scotland"),
                    ("pla", "Register of principal local authorities in Wales"),
                    ("nhsods-epraccur", "NHS organisations"),
                    ("nhsods-etr", "NHS organisations"),
                    ("nhsods-ensa", "NHS organisations"),
                    ("nhsods-eccg", "NHS organisations"),
                    ("nhsods-ecsu", "NHS organisations"),
                    ("nhsods-espha", "NHS organisations"),
                    ("nhsods-wlhb", "NHS organisations"),
                    ("nhsods-ect", "NHS organisations"),
                    ("rsl", "Registered social landlords"),
                    ("schools_gias", "Schools in England (also includes Universities)"),
                    ("schools_ni", "Schools in Northern Ireland"),
                    ("schools_scotland", "Schools in Scotland"),
                    ("schools_wales", "Schools in Wales"),
                ],
                max_length=20,
            ),
        ),
    ]
