# Generated by Django 2.2 on 2019-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_auto_20190808_1536"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("what", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
            ],
        ),
    ]
