# Generated by Django 2.2 on 2019-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_auto_20190814_1847"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status", name="when", field=models.DateTimeField(auto_now=True),
        ),
    ]
