# Generated by Django 2.2.13 on 2020-09-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0009_grant_additional_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisher", options={"ordering": ["prefix"]},
        ),
        migrations.AlterModelOptions(
            name="sourcefile", options={"ordering": ["data__publisher__prefix"]},
        ),
    ]
