# Generated by Django 2.2.20 on 2021-05-25 13:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20200916_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='getterrun',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='quality',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
