# Generated by Django 2.2.23 on 2021-06-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0014_auto_20210609_1555"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcefile",
            name="grants",
        ),
    ]
