# Generated by Django 2.2.23 on 2021-06-28 10:44

from django.db import migrations


def init_last_published(apps, schema_editor):
    Publisher = apps.get_model("db", "Publisher")

    for publisher in Publisher.objects.all():
        if publisher.data.get("last_published") == None:
            publisher.data["last_published"] = ""
            publisher.save()


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0015_remove_sourcefile_grants"),
    ]

    operations = [
        migrations.RunPython(init_last_published),
    ]
