# Generated by Django 3.2.14 on 2022-11-15 19:03

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0016_init_last_publisher_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(max_length=200)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "aggregate",
                    models.JSONField(
                        default=db.models.new_default_entity_aggregate_data
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        default=db.models.new_default_entity_additional_data
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        choices=[("GRANT", "Grant"), ("PUBLISHER", "Publisher")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(max_length=200)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "aggregate",
                    models.JSONField(
                        default=db.models.new_default_entity_aggregate_data
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        default=db.models.new_default_entity_additional_data
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        choices=[("GRANT", "Grant"), ("PUBLISHER", "Publisher")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="publisher",
            name="additional_data",
            field=models.JSONField(
                default=db.models.new_default_entity_additional_data
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="org_id",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publisher",
            name="source",
            field=models.TextField(
                choices=[("GRANT", "Grant"), ("PUBLISHER", "Publisher")], default=""
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="grant",
            name="additional_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Additional Grant data"
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="data",
            field=models.JSONField(verbose_name="Grant data"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="aggregate",
            field=models.JSONField(default=db.models.new_default_entity_aggregate_data),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="quality",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="aggregate",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="datagetter_data",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="quality",
            field=models.JSONField(null=True),
        ),
    ]
