# Generated by Django 3.2.16 on 2023-10-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0017_auto_20221115_1903"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="funder",
            constraint=models.UniqueConstraint(
                fields=("org_id",), name="funder_unique_org_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipient",
            constraint=models.UniqueConstraint(
                fields=("org_id",), name="recipient_unique_org_id"
            ),
        ),
    ]
