# Generated by Django 3.2.16 on 2023-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20221115_1903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='publisher',
            constraint=models.UniqueConstraint(fields=('org_id', 'getter_run'), name='publisher_unique_org_id'),
        ),
    ]
