# Generated by Django 3.2.16 on 2023-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20230815_1424'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='funder',
            constraint=models.UniqueConstraint(fields=('org_id',), name='funder_unique_org_id'),
        ),
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('org_id',), name='recipient_unique_org_id'),
        ),
    ]
