# Generated by Django 3.2.16 on 2024-02-26 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0019_auto_20240223_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="funding_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="publisher_org_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="recipient_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), null=True, size=None
            ),
        ),
    ]
