# Generated by Django 3.2.16 on 2024-02-27 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0021_update_grants_convenience_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="funding_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="publisher_org_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="grant",
            name="recipient_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
    ]
