# Generated by Django 3.2.16 on 2024-06-10 18:47

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0023_auto_20240318_1952"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="non_primary_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=[], size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipient",
            name="non_primary_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=[], size=None
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="funder",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["non_primary_org_ids"], name="db_funder_non_pri_745675_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["non_primary_org_ids"], name="db_recipien_non_pri_0e0ccb_gin"
            ),
        ),
    ]
