# Generated by Django 4.2.21 on 2025-10-21 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0024_auto_20240610_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="non_primary_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="non_primary_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="non_primary_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
