# Generated by Django 4.2.21 on 2025-10-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0024_auto_20240610_1847"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publisher",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="grant",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="getter_run",
        ),
    ]
