# Generated by Django 4.2.21 on 2025-10-15 21:09
from django.db import migrations, models


def delete_all_publishers(apps, schema_editor):
    # If there are duplicate Publishers with the same prefix, we need to delete them for the migration to succeed
    Publisher = apps.get_model("db", "Publisher")

    distinct_prefix_count = (
        Publisher.objects.order_by().values("prefix").distinct().count()
    )
    if Publisher.objects.count() > distinct_prefix_count:
        print(
            "\n\n"
            "WARNING: Migration db.0026 deletes all Publishers. You need to re-create them with:\n"
            "  ./manage.py manage_entities_data --update --update-publishers-only"
            "\n\n"
        )
        Publisher.objects.all().delete()
    else:
        print(
            f"Migration db.0026: No duplicate publishers found, keeping {Publisher.objects.count()} existing publishers."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0025_alter_publisher_unique_together_and_more"),
    ]

    operations = [
        # We have to clear Publishers as they are now created by manage_entities_data
        migrations.RunPython(delete_all_publishers),
        migrations.AlterField(
            model_name="publisher",
            name="prefix",
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
