# Generated by Django 4.2.21 on 2026-01-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0026_alter_publisher_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funder",
            name="org_id",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="org_id",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="org_id",
            field=models.CharField(max_length=2000),
        ),
    ]
