# Generated by Django 4.2.16 on 2024-12-10 15:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceFileMetricsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("publisher_prefix", models.TextField()),
                ("sourcefile_identifier", models.TextField()),
                ("sourcefile_url", models.TextField()),
                ("metrics", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_4d9cad_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublisherMetricsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("publisher_prefix", models.TextField()),
                ("metrics", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_c72088_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FunderMetricsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("funder_org_id", models.TextField()),
                (
                    "funder_non_primary_org_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("metrics", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_2490e5_idx"
                    )
                ],
            },
        ),
    ]
