# Generated by Django 4.2.16 on 2025-02-27 16:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoringSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("latest_getter_run_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DatasetMetricsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("metrics", models.JSONField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.monitoringsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceFileMetricsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("publisher_prefix", models.TextField()),
                ("sourcefile_identifier", models.TextField()),
                ("sourcefile_url", models.TextField()),
                ("metrics", models.JSONField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.monitoringsnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_4d9cad_idx"
                    ),
                    models.Index(
                        fields=["publisher_prefix", "sourcefile_identifier"],
                        name="monitoring__publish_b3e7c6_idx",
                    ),
                    models.Index(
                        fields=[
                            "publisher_prefix",
                            "sourcefile_identifier",
                            "timestamp",
                        ],
                        name="monitoring__publish_ba8b09_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublisherMetricsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("publisher_prefix", models.TextField()),
                ("metrics", models.JSONField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.monitoringsnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_c72088_idx"
                    ),
                    models.Index(
                        fields=["publisher_prefix"],
                        name="monitoring__publish_af876f_idx",
                    ),
                    models.Index(
                        fields=["publisher_prefix", "timestamp"],
                        name="monitoring__publish_87cddb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FunderMetricsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("funder_org_id", models.TextField()),
                (
                    "funder_non_primary_org_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("metrics", models.JSONField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitoring.monitoringsnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="monitoring__timesta_2490e5_idx"
                    ),
                    models.Index(
                        fields=["funder_org_id"], name="monitoring__funder__c8862f_idx"
                    ),
                    models.Index(
                        fields=["funder_org_id", "timestamp"],
                        name="monitoring__funder__2042d4_idx",
                    ),
                ],
            },
        ),
    ]
