# Generated by Django 4.2.21 on 2025-08-22 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundermetricsrecord",
            name="funder_non_primary_org_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, size=None
            ),
        ),
    ]
