# Generated by Django 4.2.28 on 2026-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_alter_fundermetricsrecord_funder_non_primary_org_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="authorised_domain",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="first_published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="latest_published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="org_case_safe_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="prefix",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="publisher_prefix",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="publisher_prefix_combined",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="salesforce_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="sector_organisation_subtype",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="sector_organisation_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="sectors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="self_registration_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="update_method",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="update_schedule",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundermetricsrecord",
            name="x360_giving_publisher",
            field=models.TextField(blank=True, null=True),
        ),
    ]
