name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:16.9
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: 360givingdatastore
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432/tcp
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        architecture: x64
    # For generating random data
    - run: sudo apt-get install pwgen

    - run: pip install -r requirements.txt

    # Check all apps load correctly w/o dev requirements
    - run: ./datastore/manage.py --help
    - run: ./datastore/manage.py check

    - run: pip install -r requirements_dev.txt

    - run: ./datastore/manage.py makemigrations --dry-run --check
    - run: ./datastore/manage.py migrate
    - run: coverage run --source='./datastore' ./datastore/manage.py test -v 3 tests.test_monitoring_metrics.TestMonitoringMetricsQueries.test_multiple_getterruns_in_one_day

      env:
        DATA_RUN_PID_FILE: datarunpidfile.pid
        DJANGO_SETTINGS_MODULE: settings.settings_test

    - uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fail-on-error: false
